export const levelCustom = {
  "backgroundImage": "meadow_test.png",
  "blocks": [
    {
      "x": 150,
      "y": 650,
      "moveX": 150,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 150,
      "ogY": 650
    },
    {
      "x": 150,
      "y": 600,
      "moveX": 150,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 150,
      "ogY": 600
    },
    {
      "x": 200,
      "y": 600,
      "moveX": 200,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 200,
      "ogY": 600
    },
    {
      "x": 250,
      "y": 600,
      "moveX": 250,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 250,
      "ogY": 600
    },
    {
      "x": 250,
      "y": 650,
      "moveX": 250,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 250,
      "ogY": 650
    },
    {
      "x": 350,
      "y": 550,
      "moveX": 350,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 350,
      "ogY": 550
    },
    {
      "x": 350,
      "y": 500,
      "moveX": 350,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 350,
      "ogY": 500
    },
    {
      "x": 400,
      "y": 500,
      "moveX": 400,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 400,
      "ogY": 500
    },
    {
      "x": 450,
      "y": 500,
      "moveX": 450,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 450,
      "ogY": 500
    },
    {
      "x": 450,
      "y": 550,
      "moveX": 450,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 450,
      "ogY": 550
    },
    {
      "x": 450,
      "y": 600,
      "moveX": 450,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 450,
      "ogY": 600
    },
    {
      "x": 450,
      "y": 650,
      "moveX": 450,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 450,
      "ogY": 650
    },
    {
      "x": 350,
      "y": 600,
      "moveX": 350,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 350,
      "ogY": 600
    },
    {
      "x": 350,
      "y": 650,
      "moveX": 350,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 350,
      "ogY": 650
    }
  ],
  "spikes": [],
  "ziplines": []
};