export const levelCustom = {
  "blocks": [
    {
      "x": 300,
      "y": 700,
      "moveX": 300,
      "moveY": 700,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 300,
      "ogY": 700
    },
    {
      "x": 350,
      "y": 650,
      "moveX": 350,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 350,
      "ogY": 650
    },
    {
      "x": 350,
      "y": 650,
      "moveX": 350,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 350,
      "ogY": 650
    },
    {
      "x": 400,
      "y": 600,
      "moveX": 400,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 400,
      "ogY": 600
    },
    {
      "x": 400,
      "y": 600,
      "moveX": 400,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 400,
      "ogY": 600
    },
    {
      "x": 400,
      "y": 600,
      "moveX": 400,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 400,
      "ogY": 600
    },
    {
      "x": 400,
      "y": 600,
      "moveX": 400,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 400,
      "ogY": 600
    },
    {
      "x": 400,
      "y": 600,
      "moveX": 400,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 400,
      "ogY": 600
    },
    {
      "x": 350,
      "y": 600,
      "moveX": 350,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 350,
      "ogY": 600
    },
    {
      "x": 491.5,
      "y": 620.5,
      "moveX": 500,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 500,
      "ogY": 600
    },
    {
      "x": 521.5,
      "y": 624.5,
      "moveX": 500,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 500,
      "ogY": 600
    },
    {
      "x": 500,
      "y": 650,
      "moveX": 500,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 500,
      "ogY": 650
    },
    {
      "x": 450,
      "y": 650,
      "moveX": 450,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 450,
      "ogY": 650
    },
    {
      "x": 450,
      "y": 600,
      "moveX": 450,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 450,
      "ogY": 600
    },
    {
      "x": 400,
      "y": 650,
      "moveX": 400,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 400,
      "ogY": 650
    }
  ],
  "spikes": [],
  "ziplines": []
};