export const levelCustom = {
  "backgroundImage": "level1BGT1.png",
  "blocks": [
    {
      "x": 187,
      "y": 354.5,
      "moveX": 238,
      "moveY": 381.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 238,
      "ogY": 381.5
    },
    {
      "x": 237,
      "y": 354.5,
      "moveX": 259,
      "moveY": 367.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 259,
      "ogY": 367.5
    },
    {
      "x": 285,
      "y": 354.5,
      "moveX": 319,
      "moveY": 378.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 319,
      "ogY": 378.5
    },
    {
      "x": 334,
      "y": 355.5,
      "moveX": 387,
      "moveY": 391.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 387,
      "ogY": 391.5
    },
    {
      "x": 335,
      "y": 393.5,
      "moveX": 356,
      "moveY": 419.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 356,
      "ogY": 419.5
    },
    {
      "x": 335,
      "y": 442.5,
      "moveX": 352,
      "moveY": 475.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 352,
      "ogY": 475.5
    },
    {
      "x": 335,
      "y": 490.5,
      "moveX": 346,
      "moveY": 514.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 346,
      "ogY": 514.5
    },
    {
      "x": 335,
      "y": 538.5,
      "moveX": 354,
      "moveY": 570.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 354,
      "ogY": 570.5
    },
    {
      "x": 335,
      "y": 586.5,
      "moveX": 348,
      "moveY": 613.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 348,
      "ogY": 613.5
    },
    {
      "x": 335,
      "y": 635.5,
      "moveX": 353,
      "moveY": 668.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 353,
      "ogY": 668.5
    },
    {
      "x": 334,
      "y": 684.5,
      "moveX": 355,
      "moveY": 692.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 355,
      "ogY": 692.5
    },
    {
      "x": 551,
      "y": 400.5,
      "moveX": 573,
      "moveY": 417.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 573,
      "ogY": 417.5
    },
    {
      "x": 186,
      "y": 403.5,
      "moveX": 224,
      "moveY": 434.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 224,
      "ogY": 434.5
    },
    {
      "x": 186,
      "y": 452.5,
      "moveX": 220,
      "moveY": 493.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 220,
      "ogY": 493.5
    },
    {
      "x": 186,
      "y": 500.5,
      "moveX": 214,
      "moveY": 540.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 214,
      "ogY": 540.5
    },
    {
      "x": 186,
      "y": 547.5,
      "moveX": 226,
      "moveY": 608.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 226,
      "ogY": 608.5
    },
    {
      "x": 185,
      "y": 594.5,
      "moveX": 217,
      "moveY": 638.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 217,
      "ogY": 638.5
    },
    {
      "x": 185,
      "y": 643.5,
      "moveX": 211,
      "moveY": 682.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 211,
      "ogY": 682.5
    },
    {
      "x": 550,
      "y": 450,
      "moveX": 550,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 450
    },
    {
      "x": 550,
      "y": 500,
      "moveX": 550,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 500
    },
    {
      "x": 550,
      "y": 550,
      "moveX": 550,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 550
    },
    {
      "x": 550,
      "y": 600,
      "moveX": 550,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 600
    },
    {
      "x": 550,
      "y": 650,
      "moveX": 550,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 650
    },
    {
      "x": 600,
      "y": 400,
      "moveX": 600,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 600,
      "ogY": 400
    },
    {
      "x": 650,
      "y": 400,
      "moveX": 650,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 650,
      "ogY": 400
    },
    {
      "x": 650,
      "y": 450,
      "moveX": 650,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 650,
      "ogY": 450
    },
    {
      "x": 650,
      "y": 500,
      "moveX": 650,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 650,
      "ogY": 500
    },
    {
      "x": 650,
      "y": 550,
      "moveX": 650,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 650,
      "ogY": 550
    },
    {
      "x": 650,
      "y": 600,
      "moveX": 650,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 650,
      "ogY": 600
    },
    {
      "x": 650,
      "y": 650,
      "moveX": 650,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 650,
      "ogY": 650
    },
    {
      "x": 1187,
      "y": 433.5,
      "moveX": 1195,
      "moveY": 442.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1195,
      "ogY": 442.5
    },
    {
      "x": 1187,
      "y": 481.5,
      "moveX": 1215,
      "moveY": 534.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1215,
      "ogY": 534.5
    },
    {
      "x": 1187,
      "y": 526.5,
      "moveX": 1222,
      "moveY": 569.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1222,
      "ogY": 569.5
    },
    {
      "x": 1187,
      "y": 574.5,
      "moveX": 1220,
      "moveY": 633.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1220,
      "ogY": 633.5
    },
    {
      "x": 1187,
      "y": 621.5,
      "moveX": 1213,
      "moveY": 637.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1213,
      "ogY": 637.5
    },
    {
      "x": 1187,
      "y": 669.5,
      "moveX": 1215,
      "moveY": 686.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1215,
      "ogY": 686.5
    },
    {
      "x": 1295,
      "y": 432.5,
      "moveX": 1325,
      "moveY": 497.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1325,
      "ogY": 497.5
    },
    {
      "x": 1297,
      "y": 480.5,
      "moveX": 1320,
      "moveY": 497.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1320,
      "ogY": 497.5
    },
    {
      "x": 1296,
      "y": 528.5,
      "moveX": 1318,
      "moveY": 553.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1318,
      "ogY": 553.5
    },
    {
      "x": 1296,
      "y": 576.5,
      "moveX": 1330,
      "moveY": 601.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1330,
      "ogY": 601.5
    },
    {
      "x": 1296,
      "y": 623.5,
      "moveX": 1315,
      "moveY": 684.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1315,
      "ogY": 684.5
    },
    {
      "x": 1298,
      "y": 671.5,
      "moveX": 1319,
      "moveY": 679.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1319,
      "ogY": 679.5
    },
    {
      "x": 1233,
      "y": 433.5,
      "moveX": 1253,
      "moveY": 458.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1253,
      "ogY": 458.5
    },
    {
      "x": 1267,
      "y": 433.5,
      "moveX": 1377,
      "moveY": 445.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1377,
      "ogY": 445.5
    }
  ],
  "spikes": [
    {
      "x": 400,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 450,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 500,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 350,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 700,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 750,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 800,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 850,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 900,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 950,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 1000,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 1050,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 1100,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 1150,
      "y": 650,
      "size": 50,
      "orientation": 1
    }
  ],
  "ziplines": [
    {
      "pt1X": 100,
      "pt1Y": 600,
      "pt2X": 100,
      "pt2Y": 300,
      "justJumpedOff": false,
      "jumpOffTimer": 0
    },
    {
      "pt1X": 909,
      "pt1Y": 320.5,
      "pt2X": 1204,
      "pt2Y": 275.5,
      "justJumpedOff": false,
      "jumpOffTimer": 0
    }
  ]
};