export const levelCustom = {
  "spawn": {
    "x": 50,
    "y": 500
  },
  "backgroundImage": null,
  "blocks": [
    {
      "x": 0,
      "y": 600,
      "moveX": 0,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 0,
      "ogY": 600
    },
    {
      "x": 50,
      "y": 600,
      "moveX": 50,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 50,
      "ogY": 600
    },
    {
      "x": 100,
      "y": 600,
      "moveX": 100,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 100,
      "ogY": 600
    },
    {
      "x": 150,
      "y": 600,
      "moveX": 150,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 150,
      "ogY": 600
    },
    {
      "x": 150,
      "y": 650,
      "moveX": 150,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 150,
      "ogY": 650
    },
    {
      "x": 250,
      "y": 500,
      "moveX": 250,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 250,
      "ogY": 500
    },
    {
      "x": 350,
      "y": 500,
      "moveX": 350,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 350,
      "ogY": 500
    },
    {
      "x": 300,
      "y": 500,
      "moveX": 300,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 300,
      "ogY": 500
    },
    {
      "x": 400,
      "y": 500,
      "moveX": 400,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 400,
      "ogY": 500
    },
    {
      "x": 400,
      "y": 550,
      "moveX": 400,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 400,
      "ogY": 550
    },
    {
      "x": 400,
      "y": 600,
      "moveX": 400,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 400,
      "ogY": 600
    },
    {
      "x": 400,
      "y": 650,
      "moveX": 400,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 400,
      "ogY": 650
    },
    {
      "x": 250,
      "y": 550,
      "moveX": 250,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 250,
      "ogY": 550
    },
    {
      "x": 250,
      "y": 600,
      "moveX": 250,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 250,
      "ogY": 600
    },
    {
      "x": 250,
      "y": 650,
      "moveX": 250,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 250,
      "ogY": 650
    },
    {
      "x": 0,
      "y": 650,
      "moveX": 0,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 0,
      "ogY": 650
    },
    {
      "x": 500,
      "y": 350,
      "moveX": 500,
      "moveY": 350,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 500,
      "ogY": 350
    },
    {
      "x": 500,
      "y": 400,
      "moveX": 500,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 500,
      "ogY": 400
    },
    {
      "x": 500,
      "y": 500,
      "moveX": 500,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 500,
      "ogY": 500
    },
    {
      "x": 500,
      "y": 450,
      "moveX": 500,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 500,
      "ogY": 450
    },
    {
      "x": 500,
      "y": 550,
      "moveX": 500,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 500,
      "ogY": 550
    },
    {
      "x": 500,
      "y": 600,
      "moveX": 500,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 500,
      "ogY": 600
    },
    {
      "x": 500,
      "y": 650,
      "moveX": 500,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 500,
      "ogY": 650
    },
    {
      "x": 550,
      "y": 350,
      "moveX": 550,
      "moveY": 350,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 350
    },
    {
      "x": 600,
      "y": 350,
      "moveX": 600,
      "moveY": 350,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 600,
      "ogY": 350
    },
    {
      "x": 600,
      "y": 400,
      "moveX": 600,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 600,
      "ogY": 400
    },
    {
      "x": 600,
      "y": 450,
      "moveX": 600,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 600,
      "ogY": 450
    },
    {
      "x": 600,
      "y": 500,
      "moveX": 600,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 600,
      "ogY": 500
    },
    {
      "x": 600,
      "y": 600,
      "moveX": 600,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 600,
      "ogY": 600
    },
    {
      "x": 600,
      "y": 550,
      "moveX": 600,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 600,
      "ogY": 550
    },
    {
      "x": 600,
      "y": 650,
      "moveX": 600,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 600,
      "ogY": 650
    },
    {
      "x": 500,
      "y": 100,
      "moveX": 500,
      "moveY": 50,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 500,
      "ogY": 50
    },
    {
      "x": 550,
      "y": 100,
      "moveX": 550,
      "moveY": 50,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 50
    },
    {
      "x": 600,
      "y": 100,
      "moveX": 600,
      "moveY": 50,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 600,
      "ogY": 50
    },
    {
      "x": 200,
      "y": 150,
      "moveX": 200,
      "moveY": 150,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 200,
      "ogY": 150
    },
    {
      "x": 250,
      "y": 150,
      "moveX": 250,
      "moveY": 150,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 250,
      "ogY": 150
    },
    {
      "x": 300,
      "y": 150,
      "moveX": 300,
      "moveY": 150,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 300,
      "ogY": 150
    },
    {
      "x": 150,
      "y": 200,
      "moveX": 150,
      "moveY": 200,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 150,
      "ogY": 200
    },
    {
      "x": 200,
      "y": 200,
      "moveX": 200,
      "moveY": 200,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 200,
      "ogY": 200
    }
  ],
  "spikes": [
    {
      "x": 500,
      "y": 300,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 550,
      "y": 300,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 600,
      "y": 300,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 500,
      "y": 150,
      "size": 50,
      "orientation": 3
    },
    {
      "x": 600,
      "y": 150,
      "size": 50,
      "orientation": 3
    },
    {
      "x": 550,
      "y": 150,
      "size": 50,
      "orientation": 3
    },
    {
      "x": 250,
      "y": 200,
      "size": 50,
      "orientation": 3
    },
    {
      "x": 300,
      "y": 200,
      "size": 50,
      "orientation": 3
    }
  ],
  "ziplines": [
    {
      "pt1X": 400,
      "pt1Y": 400,
      "pt2X": 50,
      "pt2Y": 250,
      "justJumpedOff": false,
      "jumpOffTimer": 0
    }
  ]
};