export const levelCustom = {
  "blocks": [
    {
      "x": 150,
      "y": 650,
      "moveX": 150,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 150,
      "ogY": 650
    },
    {
      "x": 150,
      "y": 600,
      "moveX": 150,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 150,
      "ogY": 600
    },
    {
      "x": 250,
      "y": 550,
      "moveX": 250,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 250,
      "ogY": 550
    },
    {
      "x": 250,
      "y": 600,
      "moveX": 250,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 250,
      "ogY": 600
    },
    {
      "x": 250,
      "y": 650,
      "moveX": 250,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 250,
      "ogY": 650
    },
    {
      "x": 300,
      "y": 550,
      "moveX": 300,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 300,
      "ogY": 550
    },
    {
      "x": 400,
      "y": 550,
      "moveX": 400,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 400,
      "ogY": 550
    },
    {
      "x": 350,
      "y": 550,
      "moveX": 350,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 350,
      "ogY": 550
    },
    {
      "x": 400,
      "y": 600,
      "moveX": 400,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 400,
      "ogY": 600
    },
    {
      "x": 400,
      "y": 650,
      "moveX": 400,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 400,
      "ogY": 650
    },
    {
      "x": 350,
      "y": 600,
      "moveX": 350,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 350,
      "ogY": 600
    },
    {
      "x": 300,
      "y": 600,
      "moveX": 300,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 300,
      "ogY": 600
    },
    {
      "x": 300,
      "y": 650,
      "moveX": 300,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 300,
      "ogY": 650
    },
    {
      "x": 350,
      "y": 650,
      "moveX": 350,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 350,
      "ogY": 650
    },
    {
      "x": 100,
      "y": 600,
      "moveX": 100,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 100,
      "ogY": 600
    },
    {
      "x": 100,
      "y": 650,
      "moveX": 100,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 100,
      "ogY": 650
    },
    {
      "x": 50,
      "y": 250,
      "moveX": 50,
      "moveY": 250,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 50,
      "ogY": 250
    },
    {
      "x": 0,
      "y": 250,
      "moveX": 0,
      "moveY": 250,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 0,
      "ogY": 250
    },
    {
      "x": 250,
      "y": 150,
      "moveX": 250,
      "moveY": 150,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 250,
      "ogY": 150
    },
    {
      "x": 300,
      "y": 150,
      "moveX": 300,
      "moveY": 150,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 300,
      "ogY": 150
    },
    {
      "x": 350,
      "y": 150,
      "moveX": 350,
      "moveY": 150,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 350,
      "ogY": 150
    },
    {
      "x": 350,
      "y": 200,
      "moveX": 350,
      "moveY": 200,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 350,
      "ogY": 200
    },
    {
      "x": 350,
      "y": 250,
      "moveX": 350,
      "moveY": 250,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 350,
      "ogY": 250
    },
    {
      "x": 400,
      "y": 250,
      "moveX": 400,
      "moveY": 250,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 400,
      "ogY": 250
    },
    {
      "x": 450,
      "y": 250,
      "moveX": 450,
      "moveY": 250,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 450,
      "ogY": 250
    },
    {
      "x": 500,
      "y": 250,
      "moveX": 500,
      "moveY": 250,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 500,
      "ogY": 250
    },
    {
      "x": 400,
      "y": 300,
      "moveX": 400,
      "moveY": 300,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 400,
      "ogY": 300
    },
    {
      "x": 400,
      "y": 350,
      "moveX": 400,
      "moveY": 350,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 400,
      "ogY": 350
    },
    {
      "x": 400,
      "y": 400,
      "moveX": 400,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 400,
      "ogY": 400
    },
    {
      "x": 400,
      "y": 450,
      "moveX": 400,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 400,
      "ogY": 450
    },
    {
      "x": 400,
      "y": 500,
      "moveX": 400,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 400,
      "ogY": 500
    },
    {
      "x": 600,
      "y": 100,
      "moveX": 600,
      "moveY": 100,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 600,
      "ogY": 100
    },
    {
      "x": 600,
      "y": 50,
      "moveX": 600,
      "moveY": 50,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 600,
      "ogY": 50
    },
    {
      "x": 600,
      "y": 0,
      "moveX": 600,
      "moveY": 0,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 600,
      "ogY": 0
    },
    {
      "x": 450,
      "y": 650,
      "moveX": 450,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 450,
      "ogY": 650
    },
    {
      "x": 500,
      "y": 650,
      "moveX": 500,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 500,
      "ogY": 650
    },
    {
      "x": 550,
      "y": 650,
      "moveX": 550,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 650
    },
    {
      "x": 600,
      "y": 650,
      "moveX": 600,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 600,
      "ogY": 650
    },
    {
      "x": 650,
      "y": 650,
      "moveX": 650,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 650,
      "ogY": 650
    },
    {
      "x": 700,
      "y": 650,
      "moveX": 700,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 700,
      "ogY": 650
    },
    {
      "x": 700,
      "y": 600,
      "moveX": 700,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 700,
      "ogY": 600
    },
    {
      "x": 700,
      "y": 550,
      "moveX": 700,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 700,
      "ogY": 550
    },
    {
      "x": 700,
      "y": 500,
      "moveX": 700,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 700,
      "ogY": 500
    },
    {
      "x": 750,
      "y": 500,
      "moveX": 750,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 750,
      "ogY": 500
    },
    {
      "x": 800,
      "y": 500,
      "moveX": 800,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 800,
      "ogY": 500
    },
    {
      "x": 800,
      "y": 650,
      "moveX": 800,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 800,
      "ogY": 650
    },
    {
      "x": 800,
      "y": 600,
      "moveX": 800,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 800,
      "ogY": 600
    },
    {
      "x": 750,
      "y": 600,
      "moveX": 750,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 750,
      "ogY": 600
    },
    {
      "x": 750,
      "y": 650,
      "moveX": 750,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 750,
      "ogY": 650
    },
    {
      "x": 700,
      "y": 200,
      "moveX": 700,
      "moveY": 200,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 700,
      "ogY": 200
    },
    {
      "x": 700,
      "y": 250,
      "moveX": 700,
      "moveY": 250,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 700,
      "ogY": 250
    },
    {
      "x": 700,
      "y": 150,
      "moveX": 700,
      "moveY": 150,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 700,
      "ogY": 150
    },
    {
      "x": 700,
      "y": 100,
      "moveX": 700,
      "moveY": 100,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 700,
      "ogY": 100
    },
    {
      "x": 700,
      "y": 50,
      "moveX": 700,
      "moveY": 50,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 700,
      "ogY": 50
    },
    {
      "x": 700,
      "y": 0,
      "moveX": 700,
      "moveY": 0,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 700,
      "ogY": 0
    },
    {
      "x": 1000,
      "y": 200,
      "moveX": 1000,
      "moveY": 200,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1000,
      "ogY": 200
    },
    {
      "x": 1000,
      "y": 250,
      "moveX": 1000,
      "moveY": 250,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1000,
      "ogY": 250
    },
    {
      "x": 1000,
      "y": 300,
      "moveX": 1000,
      "moveY": 300,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1000,
      "ogY": 300
    },
    {
      "x": 1000,
      "y": 350,
      "moveX": 1000,
      "moveY": 350,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1000,
      "ogY": 350
    },
    {
      "x": 1000,
      "y": 400,
      "moveX": 1000,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1000,
      "ogY": 400
    },
    {
      "x": 1000,
      "y": 450,
      "moveX": 1000,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1000,
      "ogY": 450
    },
    {
      "x": 1000,
      "y": 500,
      "moveX": 1000,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1000,
      "ogY": 500
    },
    {
      "x": 1000,
      "y": 550,
      "moveX": 1000,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1000,
      "ogY": 550
    },
    {
      "x": 1000,
      "y": 600,
      "moveX": 1000,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1000,
      "ogY": 600
    },
    {
      "x": 1000,
      "y": 650,
      "moveX": 1000,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1000,
      "ogY": 650
    },
    {
      "x": 1250,
      "y": 550,
      "moveX": 1250,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1250,
      "ogY": 550
    },
    {
      "x": 1200,
      "y": 550,
      "moveX": 1200,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1200,
      "ogY": 550
    },
    {
      "x": 1150,
      "y": 550,
      "moveX": 1150,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1150,
      "ogY": 550
    },
    {
      "x": 1150,
      "y": 600,
      "moveX": 1150,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1150,
      "ogY": 600
    },
    {
      "x": 1150,
      "y": 650,
      "moveX": 1150,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1150,
      "ogY": 650
    },
    {
      "x": 1250,
      "y": 600,
      "moveX": 1250,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1250,
      "ogY": 600
    },
    {
      "x": 1250,
      "y": 650,
      "moveX": 1250,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1250,
      "ogY": 650
    },
    {
      "x": 1300,
      "y": 400,
      "moveX": 1300,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1300,
      "ogY": 400
    },
    {
      "x": 1350,
      "y": 400,
      "moveX": 1350,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1350,
      "ogY": 400
    },
    {
      "x": 1400,
      "y": 400,
      "moveX": 1400,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1400,
      "ogY": 400
    },
    {
      "x": 1300,
      "y": 450,
      "moveX": 1300,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1300,
      "ogY": 450
    },
    {
      "x": 1300,
      "y": 550,
      "moveX": 1300,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1300,
      "ogY": 550
    },
    {
      "x": 1300,
      "y": 500,
      "moveX": 1300,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1300,
      "ogY": 500
    },
    {
      "x": 1300,
      "y": 600,
      "moveX": 1300,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1300,
      "ogY": 600
    },
    {
      "x": 1300,
      "y": 650,
      "moveX": 1300,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1300,
      "ogY": 650
    },
    {
      "x": 1200,
      "y": 600,
      "moveX": 1200,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1200,
      "ogY": 600
    },
    {
      "x": 1200,
      "y": 650,
      "moveX": 1200,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1200,
      "ogY": 650
    },
    {
      "x": 1350,
      "y": 450,
      "moveX": 1350,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1350,
      "ogY": 450
    },
    {
      "x": 1400,
      "y": 450,
      "moveX": 1400,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1400,
      "ogY": 450
    },
    {
      "x": 1400,
      "y": 500,
      "moveX": 1400,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1400,
      "ogY": 500
    },
    {
      "x": 1350,
      "y": 500,
      "moveX": 1350,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1350,
      "ogY": 500
    },
    {
      "x": 1350,
      "y": 600,
      "moveX": 1350,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1350,
      "ogY": 600
    },
    {
      "x": 1350,
      "y": 550,
      "moveX": 1350,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1350,
      "ogY": 550
    },
    {
      "x": 1400,
      "y": 550,
      "moveX": 1400,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1400,
      "ogY": 550
    },
    {
      "x": 1400,
      "y": 600,
      "moveX": 1400,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1400,
      "ogY": 600
    },
    {
      "x": 1400,
      "y": 650,
      "moveX": 1400,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1400,
      "ogY": 650
    },
    {
      "x": 1350,
      "y": 650,
      "moveX": 1350,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1350,
      "ogY": 650
    },
    {
      "x": 650,
      "y": 550,
      "moveX": 650,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 650,
      "ogY": 550
    },
    {
      "x": 650,
      "y": 600,
      "moveX": 650,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 650,
      "ogY": 600
    }
  ],
  "spikes": [
    {
      "x": 200,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 50,
      "y": 200,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 0,
      "y": 200,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 300,
      "y": 200,
      "size": 50,
      "orientation": 4
    },
    {
      "x": 300,
      "y": 250,
      "size": 50,
      "orientation": 4
    },
    {
      "x": 350,
      "y": 100,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 400,
      "y": 200,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 350,
      "y": 500,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 550,
      "y": 100,
      "size": 50,
      "orientation": 4
    },
    {
      "x": 450,
      "y": 600,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 500,
      "y": 600,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 550,
      "y": 600,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 600,
      "y": 600,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 650,
      "y": 250,
      "size": 50,
      "orientation": 4
    },
    {
      "x": 1000,
      "y": 150,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 950,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 900,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 850,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 1150,
      "y": 500,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 1200,
      "y": 500,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 1250,
      "y": 500,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 1100,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 1050,
      "y": 650,
      "size": 50,
      "orientation": 1
    }
  ],
  "ziplines": [
    {
      "pt1X": 349.5,
      "pt1Y": 449.5,
      "pt2X": 99.5,
      "pt2Y": 150.5,
      "justJumpedOff": false,
      "jumpOffTimer": 0
    },
    {
      "pt1X": 625,
      "pt1Y": 226,
      "pt2X": 543.5,
      "pt2Y": 675.5,
      "justJumpedOff": false,
      "jumpOffTimer": 0
    },
    {
      "pt1X": 900.5,
      "pt1Y": 449.5,
      "pt2X": 948.5,
      "pt2Y": 199.5,
      "justJumpedOff": false,
      "jumpOffTimer": 0
    },
    {
      "pt1X": 1098.5,
      "pt1Y": 105.5,
      "pt2X": 1199.5,
      "pt2Y": 448.5,
      "justJumpedOff": false,
      "jumpOffTimer": 0
    }
  ]
};