export const levelCustom = {
  "blocks": [
    {
      "x": 200,
      "y": 550,
      "moveX": 200,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 200,
      "ogY": 550
    },
    {
      "x": 150,
      "y": 550,
      "moveX": 150,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 150,
      "ogY": 550
    },
    {
      "x": 100,
      "y": 550,
      "moveX": 100,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 100,
      "ogY": 550
    },
    {
      "x": 100,
      "y": 600,
      "moveX": 100,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 100,
      "ogY": 600
    },
    {
      "x": 100,
      "y": 650,
      "moveX": 100,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 100,
      "ogY": 650
    },
    {
      "x": 300,
      "y": 350,
      "moveX": 300,
      "moveY": 350,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 300,
      "ogY": 350
    },
    {
      "x": 350,
      "y": 350,
      "moveX": 350,
      "moveY": 350,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 350,
      "ogY": 350
    },
    {
      "x": 300,
      "y": 50,
      "moveX": 300,
      "moveY": 0,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 300,
      "ogY": 0
    },
    {
      "x": 350,
      "y": 50,
      "moveX": 350,
      "moveY": 0,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 350,
      "ogY": 0
    },
    {
      "x": 450,
      "y": 300,
      "moveX": 450,
      "moveY": 300,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 450,
      "ogY": 300
    },
    {
      "x": 550,
      "y": 300,
      "moveX": 550,
      "moveY": 300,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 300
    },
    {
      "x": 450,
      "y": 350,
      "moveX": 450,
      "moveY": 350,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 450,
      "ogY": 350
    },
    {
      "x": 450,
      "y": 400,
      "moveX": 450,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 450,
      "ogY": 400
    },
    {
      "x": 550,
      "y": 400,
      "moveX": 550,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 400
    },
    {
      "x": 550,
      "y": 350,
      "moveX": 550,
      "moveY": 350,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 350
    },
    {
      "x": 550,
      "y": 200,
      "moveX": 550,
      "moveY": 200,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 200
    },
    {
      "x": 550,
      "y": 250,
      "moveX": 550,
      "moveY": 250,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 250
    },
    {
      "x": 550,
      "y": 150,
      "moveX": 550,
      "moveY": 150,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 150
    },
    {
      "x": 750,
      "y": 550,
      "moveX": 750,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 750,
      "ogY": 550
    },
    {
      "x": 750,
      "y": 600,
      "moveX": 750,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 750,
      "ogY": 600
    },
    {
      "x": 750,
      "y": 650,
      "moveX": 750,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 750,
      "ogY": 650
    },
    {
      "x": 750,
      "y": 300,
      "moveX": 750,
      "moveY": 300,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 750,
      "ogY": 300
    },
    {
      "x": 750,
      "y": 150,
      "moveX": 750,
      "moveY": 150,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 750,
      "ogY": 150
    },
    {
      "x": 950,
      "y": 300,
      "moveX": 950,
      "moveY": 300,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 950,
      "ogY": 300
    },
    {
      "x": 950,
      "y": 550,
      "moveX": 950,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 950,
      "ogY": 550
    },
    {
      "x": 950,
      "y": 600,
      "moveX": 950,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 950,
      "ogY": 600
    },
    {
      "x": 950,
      "y": 650,
      "moveX": 950,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 950,
      "ogY": 650
    },
    {
      "x": 700,
      "y": 550,
      "moveX": 700,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 700,
      "ogY": 550
    },
    {
      "x": 750,
      "y": 500,
      "moveX": 750,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 750,
      "ogY": 500
    },
    {
      "x": 700,
      "y": 600,
      "moveX": 700,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 700,
      "ogY": 600
    },
    {
      "x": 700,
      "y": 650,
      "moveX": 700,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 700,
      "ogY": 650
    },
    {
      "x": 950,
      "y": 250,
      "moveX": 950,
      "moveY": 250,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 950,
      "ogY": 250
    },
    {
      "x": 950,
      "y": 200,
      "moveX": 950,
      "moveY": 200,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 950,
      "ogY": 200
    },
    {
      "x": 950,
      "y": 150,
      "moveX": 950,
      "moveY": 150,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 950,
      "ogY": 150
    },
    {
      "x": 950,
      "y": 100,
      "moveX": 950,
      "moveY": 100,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 950,
      "ogY": 100
    },
    {
      "x": 950,
      "y": 0,
      "moveX": 950,
      "moveY": 0,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 950,
      "ogY": 0
    },
    {
      "x": 1050,
      "y": 550,
      "moveX": 1050,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1050,
      "ogY": 550
    },
    {
      "x": 1050,
      "y": 600,
      "moveX": 1050,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1050,
      "ogY": 600
    },
    {
      "x": 1050,
      "y": 650,
      "moveX": 1050,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1050,
      "ogY": 650
    },
    {
      "x": 1150,
      "y": 550,
      "moveX": 1150,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1150,
      "ogY": 550
    },
    {
      "x": 1150,
      "y": 600,
      "moveX": 1150,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1150,
      "ogY": 600
    },
    {
      "x": 1150,
      "y": 650,
      "moveX": 1150,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1150,
      "ogY": 650
    },
    {
      "x": 800,
      "y": 150,
      "moveX": 795,
      "moveY": 75.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 795,
      "ogY": 75.5
    },
    {
      "x": 1150,
      "y": 150,
      "moveX": 1150,
      "moveY": 150,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1150,
      "ogY": 150
    },
    {
      "x": 1200,
      "y": 150,
      "moveX": 1200,
      "moveY": 150,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1200,
      "ogY": 150
    },
    {
      "x": 1250,
      "y": 450,
      "moveX": 1250,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1250,
      "ogY": 450
    },
    {
      "x": 1250,
      "y": 400,
      "moveX": 1250,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1250,
      "ogY": 400
    },
    {
      "x": 1250,
      "y": 500,
      "moveX": 1250,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1250,
      "ogY": 500
    },
    {
      "x": 1250,
      "y": 550,
      "moveX": 1250,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1250,
      "ogY": 550
    },
    {
      "x": 1250,
      "y": 600,
      "moveX": 1250,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1250,
      "ogY": 600
    },
    {
      "x": 1250,
      "y": 650,
      "moveX": 1250,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1250,
      "ogY": 650
    },
    {
      "x": 1200,
      "y": 550,
      "moveX": 1200,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1200,
      "ogY": 550
    },
    {
      "x": 1200,
      "y": 600,
      "moveX": 1200,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1200,
      "ogY": 600
    },
    {
      "x": 1200,
      "y": 650,
      "moveX": 1200,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1200,
      "ogY": 650
    },
    {
      "x": 1250,
      "y": 150,
      "moveX": 1300,
      "moveY": 150,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1300,
      "ogY": 150
    },
    {
      "x": 1300,
      "y": 350,
      "moveX": 1300,
      "moveY": 350,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1300,
      "ogY": 350
    },
    {
      "x": 1350,
      "y": 350,
      "moveX": 1350,
      "moveY": 350,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1350,
      "ogY": 350
    },
    {
      "x": 1400,
      "y": 350,
      "moveX": 1400,
      "moveY": 350,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1400,
      "ogY": 350
    },
    {
      "x": 50,
      "y": 350,
      "moveX": 50,
      "moveY": 350,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 50,
      "ogY": 350
    },
    {
      "x": 100,
      "y": 350,
      "moveX": 100,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 100,
      "ogY": 400
    },
    {
      "x": 1100,
      "y": 400,
      "moveX": 1100,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1100,
      "ogY": 400
    },
    {
      "x": 1050,
      "y": 400,
      "moveX": 1050,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1050,
      "ogY": 400
    },
    {
      "x": 1100,
      "y": 350,
      "moveX": 1100,
      "moveY": 350,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1100,
      "ogY": 350
    },
    {
      "x": 1100,
      "y": 566.5,
      "moveX": 1108,
      "moveY": 634.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1108,
      "ogY": 634.5
    },
    {
      "x": 1100,
      "y": 600,
      "moveX": 1100,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1100,
      "ogY": 600
    },
    {
      "x": 1100,
      "y": 650,
      "moveX": 1100,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1100,
      "ogY": 650
    },
    {
      "x": 1233,
      "y": 450.5,
      "moveX": 1193,
      "moveY": 429.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1193,
      "ogY": 429.5
    },
    {
      "x": 1115,
      "y": 350.5,
      "moveX": 1166,
      "moveY": 367.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1166,
      "ogY": 367.5
    },
    {
      "x": 1276,
      "y": 350,
      "moveX": 1250,
      "moveY": 350,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1250,
      "ogY": 350
    },
    {
      "x": 950,
      "y": 330,
      "moveX": 950,
      "moveY": 350,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 950,
      "ogY": 350
    },
    {
      "x": 812,
      "y": 149.5,
      "moveX": 926,
      "moveY": 92.5,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 926,
      "ogY": 92.5
    },
    {
      "x": 950,
      "y": 50,
      "moveX": 950,
      "moveY": 50,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 950,
      "ogY": 50
    }
  ],
  "spikes": [
    {
      "x": 150,
      "y": 500,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 200,
      "y": 500,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 100,
      "y": 500,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 150,
      "y": 350,
      "size": 50,
      "orientation": 2
    },
    {
      "x": 250,
      "y": 350,
      "size": 50,
      "orientation": 4
    },
    {
      "x": 300,
      "y": 300,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 350,
      "y": 300,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 300,
      "y": 100,
      "size": 50,
      "orientation": 3
    },
    {
      "x": 350,
      "y": 100,
      "size": 50,
      "orientation": 3
    },
    {
      "x": 600,
      "y": 300,
      "size": 50,
      "orientation": 2
    },
    {
      "x": 600,
      "y": 350,
      "size": 50,
      "orientation": 2
    },
    {
      "x": 450,
      "y": 250,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 150,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 200,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 250,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 300,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 350,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 400,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 450,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 500,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 650,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 650,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 750,
      "y": 250,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 750,
      "y": 350,
      "size": 50,
      "orientation": 3
    },
    {
      "x": 750,
      "y": 200,
      "size": 50,
      "orientation": 3
    },
    {
      "x": 550,
      "y": 100,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 862,
      "y": 150,
      "size": 50,
      "orientation": 2
    },
    {
      "x": 800,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 850,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 900,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 750,
      "y": 450,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 950,
      "y": 500,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 1100,
      "y": 518,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 1000,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 1000,
      "y": 200,
      "size": 50,
      "orientation": 2
    },
    {
      "x": 1000,
      "y": 150,
      "size": 50,
      "orientation": 2
    },
    {
      "x": 1200,
      "y": 100,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 1250,
      "y": 200,
      "size": 50,
      "orientation": 3
    },
    {
      "x": 1251,
      "y": 0,
      "size": 50,
      "orientation": 3
    },
    {
      "x": 1350,
      "y": 300,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 1300,
      "y": 300,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 50,
      "y": 400,
      "size": 50,
      "orientation": 3
    },
    {
      "x": 100,
      "y": 100,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 100,
      "y": 300,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 100,
      "y": 250,
      "size": 50,
      "orientation": 3
    },
    {
      "x": 100,
      "y": 150,
      "size": 50,
      "orientation": 3
    },
    {
      "x": 100,
      "y": 200,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 150,
      "y": 100,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 150,
      "y": 149,
      "size": 50,
      "orientation": 3
    },
    {
      "x": 800,
      "y": 100,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 1191,
      "y": 500,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 1050,
      "y": 350,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 1227,
      "y": 350.5,
      "size": 50,
      "orientation": 4
    },
    {
      "x": 1150,
      "y": -50,
      "size": 50,
      "orientation": 3
    },
    {
      "x": 550,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 600,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 950,
      "y": 379.5,
      "size": 50,
      "orientation": 3
    },
    {
      "x": 476,
      "y": 299.5,
      "size": 50,
      "orientation": 2
    },
    {
      "x": 475,
      "y": 347.5,
      "size": 50,
      "orientation": 2
    },
    {
      "x": 726,
      "y": 498.5,
      "size": 50,
      "orientation": 4
    },
    {
      "x": 1000,
      "y": 100,
      "size": 50,
      "orientation": 2
    },
    {
      "x": 1000,
      "y": 50,
      "size": 50,
      "orientation": 2
    },
    {
      "x": 1000,
      "y": 0,
      "size": 50,
      "orientation": 2
    }
  ],
  "ziplines": [
    {
      "pt1X": 0,
      "pt1Y": 550,
      "pt2X": 68,
      "pt2Y": 116,
      "justJumpedOff": false,
      "jumpOffTimer": 0
    },
    {
      "pt1X": 199,
      "pt1Y": 202,
      "pt2X": 150,
      "pt2Y": 575,
      "justJumpedOff": false,
      "jumpOffTimer": 0
    },
    {
      "pt1X": 350,
      "pt1Y": 100,
      "pt2X": 350,
      "pt2Y": 350,
      "justJumpedOff": false,
      "jumpOffTimer": 0
    },
    {
      "pt1X": 528,
      "pt1Y": 527,
      "pt2X": 576,
      "pt2Y": 629,
      "justJumpedOff": false,
      "jumpOffTimer": 0
    },
    {
      "pt1X": 700,
      "pt1Y": 427,
      "pt2X": 649,
      "pt2Y": 200,
      "justJumpedOff": false,
      "jumpOffTimer": 0
    },
    {
      "pt1X": 851,
      "pt1Y": 251,
      "pt2X": 848,
      "pt2Y": 700,
      "justJumpedOff": false,
      "jumpOffTimer": 0
    },
    {
      "pt1X": 1250,
      "pt1Y": 300,
      "pt2X": 1000,
      "pt2Y": 200,
      "justJumpedOff": false,
      "jumpOffTimer": 0
    },
    {
      "pt1X": 1350,
      "pt1Y": 150,
      "pt2X": 1379,
      "pt2Y": 274,
      "justJumpedOff": false,
      "jumpOffTimer": 0
    }
  ]
};