export const levelCustom = {
  "blocks": [
    {
      "x": 100,
      "y": 650,
      "moveX": 100,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 100,
      "ogY": 650
    },
    {
      "x": 100,
      "y": 600,
      "moveX": 100,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 100,
      "ogY": 600
    },
    {
      "x": 150,
      "y": 600,
      "moveX": 150,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 150,
      "ogY": 600
    },
    {
      "x": 200,
      "y": 600,
      "moveX": 200,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 200,
      "ogY": 600
    },
    {
      "x": 200,
      "y": 650,
      "moveX": 200,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 200,
      "ogY": 650
    },
    {
      "x": 150,
      "y": 650,
      "moveX": 150,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 150,
      "ogY": 650
    },
    {
      "x": 300,
      "y": 550,
      "moveX": 300,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 300,
      "ogY": 550
    },
    {
      "x": 300,
      "y": 600,
      "moveX": 300,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 300,
      "ogY": 600
    },
    {
      "x": 350,
      "y": 600,
      "moveX": 350,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 350,
      "ogY": 600
    },
    {
      "x": 350,
      "y": 550,
      "moveX": 350,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 350,
      "ogY": 550
    },
    {
      "x": 450,
      "y": 450,
      "moveX": 450,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 450,
      "ogY": 450
    },
    {
      "x": 450,
      "y": 500,
      "moveX": 450,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 450,
      "ogY": 500
    },
    {
      "x": 500,
      "y": 500,
      "moveX": 500,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 500,
      "ogY": 500
    },
    {
      "x": 500,
      "y": 450,
      "moveX": 500,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 500,
      "ogY": 450
    },
    {
      "x": 200,
      "y": 300,
      "moveX": 200,
      "moveY": 300,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 200,
      "ogY": 300
    },
    {
      "x": 150,
      "y": 100,
      "moveX": 150,
      "moveY": 100,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 150,
      "ogY": 100
    },
    {
      "x": 400,
      "y": 150,
      "moveX": 400,
      "moveY": 150,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 400,
      "ogY": 150
    },
    {
      "x": 450,
      "y": 150,
      "moveX": 450,
      "moveY": 150,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 450,
      "ogY": 150
    },
    {
      "x": 550,
      "y": 300,
      "moveX": 550,
      "moveY": 300,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 300
    },
    {
      "x": 600,
      "y": 300,
      "moveX": 600,
      "moveY": 300,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 600,
      "ogY": 300
    },
    {
      "x": 550,
      "y": 350,
      "moveX": 550,
      "moveY": 350,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 350
    },
    {
      "x": 550,
      "y": 400,
      "moveX": 550,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 400
    },
    {
      "x": 550,
      "y": 450,
      "moveX": 550,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 450
    },
    {
      "x": 550,
      "y": 500,
      "moveX": 550,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 500
    },
    {
      "x": 550,
      "y": 550,
      "moveX": 550,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 550
    },
    {
      "x": 550,
      "y": 600,
      "moveX": 550,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 600
    },
    {
      "x": 550,
      "y": 650,
      "moveX": 550,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 650
    },
    {
      "x": 300,
      "y": 650,
      "moveX": 300,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 300,
      "ogY": 650
    },
    {
      "x": 350,
      "y": 650,
      "moveX": 350,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 350,
      "ogY": 650
    },
    {
      "x": 700,
      "y": 450,
      "moveX": 700,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 700,
      "ogY": 450
    },
    {
      "x": 750,
      "y": 450,
      "moveX": 750,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 750,
      "ogY": 450
    },
    {
      "x": 650,
      "y": 550,
      "moveX": 650,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 650,
      "ogY": 550
    },
    {
      "x": 600,
      "y": 550,
      "moveX": 600,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 600,
      "ogY": 550
    },
    {
      "x": 700,
      "y": 650,
      "moveX": 700,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 700,
      "ogY": 650
    },
    {
      "x": 750,
      "y": 650,
      "moveX": 750,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 750,
      "ogY": 650
    },
    {
      "x": 850,
      "y": 650,
      "moveX": 850,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 850,
      "ogY": 650
    },
    {
      "x": 800,
      "y": 650,
      "moveX": 800,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 800,
      "ogY": 650
    },
    {
      "x": 900,
      "y": 650,
      "moveX": 900,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 900,
      "ogY": 650
    },
    {
      "x": 700,
      "y": 200,
      "moveX": 700,
      "moveY": 200,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 700,
      "ogY": 200
    },
    {
      "x": 850,
      "y": 150,
      "moveX": 850,
      "moveY": 150,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 850,
      "ogY": 150
    },
    {
      "x": 900,
      "y": 150,
      "moveX": 900,
      "moveY": 150,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 900,
      "ogY": 150
    },
    {
      "x": 800,
      "y": 150,
      "moveX": 800,
      "moveY": 150,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 800,
      "ogY": 150
    },
    {
      "x": 1100,
      "y": 100,
      "moveX": 1100,
      "moveY": 100,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1100,
      "ogY": 100
    },
    {
      "x": 1150,
      "y": 100,
      "moveX": 1150,
      "moveY": 100,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1150,
      "ogY": 100
    },
    {
      "x": 1200,
      "y": 100,
      "moveX": 1200,
      "moveY": 100,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1200,
      "ogY": 100
    },
    {
      "x": 1250,
      "y": 100,
      "moveX": 1250,
      "moveY": 100,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1250,
      "ogY": 100
    },
    {
      "x": 1100,
      "y": 150,
      "moveX": 1100,
      "moveY": 150,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1100,
      "ogY": 150
    },
    {
      "x": 1100,
      "y": 200,
      "moveX": 1100,
      "moveY": 200,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1100,
      "ogY": 200
    },
    {
      "x": 1100,
      "y": 250,
      "moveX": 1100,
      "moveY": 250,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1100,
      "ogY": 250
    },
    {
      "x": 1100,
      "y": 300,
      "moveX": 1100,
      "moveY": 300,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1100,
      "ogY": 300
    },
    {
      "x": 1100,
      "y": 350,
      "moveX": 1100,
      "moveY": 350,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1100,
      "ogY": 350
    },
    {
      "x": 1100,
      "y": 400,
      "moveX": 1100,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1100,
      "ogY": 400
    },
    {
      "x": 1100,
      "y": 450,
      "moveX": 1100,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1100,
      "ogY": 450
    },
    {
      "x": 1100,
      "y": 500,
      "moveX": 1100,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1100,
      "ogY": 500
    },
    {
      "x": 1100,
      "y": 550,
      "moveX": 1100,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1100,
      "ogY": 550
    },
    {
      "x": 1100,
      "y": 600,
      "moveX": 1100,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1100,
      "ogY": 600
    },
    {
      "x": 1100,
      "y": 650,
      "moveX": 1100,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1100,
      "ogY": 650
    },
    {
      "x": 1150,
      "y": 650,
      "moveX": 1150,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1150,
      "ogY": 650
    },
    {
      "x": 1200,
      "y": 650,
      "moveX": 1200,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1200,
      "ogY": 650
    },
    {
      "x": 1250,
      "y": 650,
      "moveX": 1250,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1250,
      "ogY": 650
    },
    {
      "x": 1250,
      "y": 600,
      "moveX": 1250,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1250,
      "ogY": 600
    },
    {
      "x": 1200,
      "y": 600,
      "moveX": 1200,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1200,
      "ogY": 600
    },
    {
      "x": 1150,
      "y": 600,
      "moveX": 1150,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1150,
      "ogY": 600
    },
    {
      "x": 1150,
      "y": 550,
      "moveX": 1150,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1150,
      "ogY": 550
    },
    {
      "x": 1200,
      "y": 550,
      "moveX": 1200,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1200,
      "ogY": 550
    },
    {
      "x": 1250,
      "y": 550,
      "moveX": 1250,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1250,
      "ogY": 550
    },
    {
      "x": 1250,
      "y": 500,
      "moveX": 1250,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1250,
      "ogY": 500
    },
    {
      "x": 1200,
      "y": 500,
      "moveX": 1200,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1200,
      "ogY": 500
    },
    {
      "x": 1150,
      "y": 500,
      "moveX": 1150,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1150,
      "ogY": 500
    },
    {
      "x": 1150,
      "y": 450,
      "moveX": 1150,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1150,
      "ogY": 450
    },
    {
      "x": 1200,
      "y": 450,
      "moveX": 1200,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1200,
      "ogY": 450
    },
    {
      "x": 1250,
      "y": 450,
      "moveX": 1250,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1250,
      "ogY": 450
    },
    {
      "x": 1250,
      "y": 400,
      "moveX": 1250,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1250,
      "ogY": 400
    },
    {
      "x": 1200,
      "y": 400,
      "moveX": 1200,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1200,
      "ogY": 400
    },
    {
      "x": 1150,
      "y": 400,
      "moveX": 1150,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1150,
      "ogY": 400
    },
    {
      "x": 1150,
      "y": 350,
      "moveX": 1150,
      "moveY": 350,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1150,
      "ogY": 350
    },
    {
      "x": 1250,
      "y": 350,
      "moveX": 1250,
      "moveY": 350,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1250,
      "ogY": 350
    },
    {
      "x": 1200,
      "y": 350,
      "moveX": 1200,
      "moveY": 350,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1200,
      "ogY": 350
    },
    {
      "x": 1250,
      "y": 300,
      "moveX": 1250,
      "moveY": 300,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1250,
      "ogY": 300
    },
    {
      "x": 1200,
      "y": 300,
      "moveX": 1200,
      "moveY": 300,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1200,
      "ogY": 300
    },
    {
      "x": 1150,
      "y": 300,
      "moveX": 1150,
      "moveY": 300,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1150,
      "ogY": 300
    },
    {
      "x": 1150,
      "y": 250,
      "moveX": 1150,
      "moveY": 250,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1150,
      "ogY": 250
    },
    {
      "x": 1200,
      "y": 250,
      "moveX": 1200,
      "moveY": 250,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1200,
      "ogY": 250
    },
    {
      "x": 1250,
      "y": 250,
      "moveX": 1250,
      "moveY": 250,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1250,
      "ogY": 250
    },
    {
      "x": 1250,
      "y": 200,
      "moveX": 1250,
      "moveY": 200,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1250,
      "ogY": 200
    },
    {
      "x": 1200,
      "y": 200,
      "moveX": 1200,
      "moveY": 200,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1200,
      "ogY": 200
    },
    {
      "x": 1150,
      "y": 200,
      "moveX": 1150,
      "moveY": 200,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1150,
      "ogY": 200
    },
    {
      "x": 1150,
      "y": 150,
      "moveX": 1150,
      "moveY": 150,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1150,
      "ogY": 150
    },
    {
      "x": 1200,
      "y": 150,
      "moveX": 1200,
      "moveY": 150,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1200,
      "ogY": 150
    },
    {
      "x": 1250,
      "y": 150,
      "moveX": 1250,
      "moveY": 150,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 1250,
      "ogY": 150
    }
  ],
  "spikes": [
    {
      "x": 250,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 400,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 450,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 500,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 200,
      "y": 250,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 150,
      "y": 300,
      "size": 50,
      "orientation": 4
    },
    {
      "x": 350,
      "y": 150,
      "size": 50,
      "orientation": 4
    },
    {
      "x": 550,
      "y": 250,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 650,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 600,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 750,
      "y": 400,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 600,
      "y": 500,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 850,
      "y": 600,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 900,
      "y": 600,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 700,
      "y": 150,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 800,
      "y": 100,
      "size": 50,
      "orientation": 1
    }
  ],
  "ziplines": [
    {
      "pt1X": 499.5,
      "pt1Y": 400.5,
      "pt2X": 299.5,
      "pt2Y": 251.5,
      "justJumpedOff": false,
      "jumpOffTimer": 0
    },
    {
      "pt1X": 149.5,
      "pt1Y": 298.5,
      "pt2X": 75.5,
      "pt2Y": 124.5,
      "justJumpedOff": false,
      "jumpOffTimer": 0
    },
    {
      "pt1X": 1001.5,
      "pt1Y": 600.5,
      "pt2X": 1025.5,
      "pt2Y": 213.5,
      "justJumpedOff": false,
      "jumpOffTimer": 0
    }
  ]
};