export const levelCustom = {
  "backgroundImage": "level1BGT1.png",
  "blocks": [
    {
      "x": 286,
      "y": 350,
      "moveX": 300,
      "moveY": 150,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 300,
      "ogY": 150
    },
    {
      "x": 236,
      "y": 350,
      "moveX": 250,
      "moveY": 150,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 250,
      "ogY": 150
    },
    {
      "x": 328,
      "y": 350,
      "moveX": 350,
      "moveY": 150,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 350,
      "ogY": 150
    },
    {
      "x": 186,
      "y": 350,
      "moveX": 200,
      "moveY": 200,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 200,
      "ogY": 200
    },
    {
      "x": 186,
      "y": 400,
      "moveX": 200,
      "moveY": 250,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 200,
      "ogY": 250
    },
    {
      "x": 186,
      "y": 450,
      "moveX": 200,
      "moveY": 300,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 200,
      "ogY": 300
    },
    {
      "x": 186,
      "y": 500,
      "moveX": 200,
      "moveY": 350,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 200,
      "ogY": 350
    },
    {
      "x": 186,
      "y": 550,
      "moveX": 200,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 200,
      "ogY": 400
    },
    {
      "x": 186,
      "y": 600,
      "moveX": 200,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 200,
      "ogY": 450
    },
    {
      "x": 186,
      "y": 650,
      "moveX": 200,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 200,
      "ogY": 500
    },
    {
      "x": 186,
      "y": 700,
      "moveX": 200,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 200,
      "ogY": 550
    },
    {
      "x": 186,
      "y": 750,
      "moveX": 200,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 200,
      "ogY": 600
    },
    {
      "x": 327,
      "y": 351,
      "moveX": 200,
      "moveY": 200,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 200,
      "ogY": 200
    },
    {
      "x": 327,
      "y": 401,
      "moveX": 200,
      "moveY": 250,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 200,
      "ogY": 250
    },
    {
      "x": 327,
      "y": 451,
      "moveX": 200,
      "moveY": 300,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 200,
      "ogY": 300
    },
    {
      "x": 327,
      "y": 501,
      "moveX": 200,
      "moveY": 350,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 200,
      "ogY": 350
    },
    {
      "x": 327,
      "y": 551,
      "moveX": 200,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 200,
      "ogY": 400
    },
    {
      "x": 327,
      "y": 601,
      "moveX": 200,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 200,
      "ogY": 450
    },
    {
      "x": 327,
      "y": 651,
      "moveX": 200,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 200,
      "ogY": 500
    },
    {
      "x": 650,
      "y": 400,
      "moveX": 650,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 650,
      "ogY": 400
    },
    {
      "x": 600,
      "y": 400,
      "moveX": 600,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 600,
      "ogY": 400
    },
    {
      "x": 550,
      "y": 400,
      "moveX": 550,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 400
    },
    {
      "x": 650,
      "y": 450,
      "moveX": 650,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 650,
      "ogY": 450
    },
    {
      "x": 650,
      "y": 500,
      "moveX": 650,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 650,
      "ogY": 500
    },
    {
      "x": 650,
      "y": 550,
      "moveX": 650,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 650,
      "ogY": 550
    },
    {
      "x": 650,
      "y": 600,
      "moveX": 650,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 650,
      "ogY": 600
    },
    {
      "x": 650,
      "y": 650,
      "moveX": 650,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 650,
      "ogY": 650
    },
    {
      "x": 550,
      "y": 450,
      "moveX": 550,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 450
    },
    {
      "x": 550,
      "y": 550,
      "moveX": 550,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 550
    },
    {
      "x": 550,
      "y": 500,
      "moveX": 550,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 500
    },
    {
      "x": 550,
      "y": 600,
      "moveX": 550,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 600
    },
    {
      "x": 550,
      "y": 650,
      "moveX": 550,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 650
    },
    {
      "x": 1287,
      "y": 434,
      "moveX": 650,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 650,
      "ogY": 400
    },
    {
      "x": 1237,
      "y": 434,
      "moveX": 600,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 600,
      "ogY": 400
    },
    {
      "x": 1187,
      "y": 434,
      "moveX": 550,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 400
    },
    {
      "x": 1187,
      "y": 484,
      "moveX": 550,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 450
    },
    {
      "x": 1187,
      "y": 534,
      "moveX": 550,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 500
    },
    {
      "x": 1187,
      "y": 584,
      "moveX": 550,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 550
    },
    {
      "x": 1187,
      "y": 634,
      "moveX": 550,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 600
    },
    {
      "x": 1187,
      "y": 684,
      "moveX": 550,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 550,
      "ogY": 650
    },
    {
      "x": 1287,
      "y": 684,
      "moveX": 650,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 650,
      "ogY": 650
    },
    {
      "x": 1287,
      "y": 634,
      "moveX": 650,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 650,
      "ogY": 600
    },
    {
      "x": 1287,
      "y": 584,
      "moveX": 650,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 650,
      "ogY": 550
    },
    {
      "x": 1287,
      "y": 534,
      "moveX": 650,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 650,
      "ogY": 500
    },
    {
      "x": 1287,
      "y": 484,
      "moveX": 650,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 650,
      "ogY": 450
    }
  ],
  "spikes": [
    {
      "x": 700,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 750,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 800,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 850,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 900,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 950,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 1000,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 1050,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 1100,
      "y": 650,
      "size": 50,
      "orientation": 1
    },
    {
      "x": 1150,
      "y": 650,
      "size": 50,
      "orientation": 1
    }
  ],
  "ziplines": [
    {
      "pt1X": 100,
      "pt1Y": 600,
      "pt2X": 100,
      "pt2Y": 300,
      "justJumpedOff": false,
      "jumpOffTimer": 0
    },
    {
      "pt1X": 909,
      "pt1Y": 350.5,
      "pt2X": 1203,
      "pt2Y": 306.5,
      "justJumpedOff": false,
      "jumpOffTimer": 0
    }
  ]
};