export const levelCustom = {
  "backgroundImage": null,
  "blocks": [
    {
      "x": 200,
      "y": 650,
      "moveX": 200,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 200,
      "ogY": 650
    },
    {
      "x": 200,
      "y": 600,
      "moveX": 200,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 200,
      "ogY": 600
    },
    {
      "x": 250,
      "y": 600,
      "moveX": 250,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 250,
      "ogY": 600
    },
    {
      "x": 300,
      "y": 600,
      "moveX": 300,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 300,
      "ogY": 600
    },
    {
      "x": 300,
      "y": 650,
      "moveX": 300,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 300,
      "ogY": 650
    },
    {
      "x": 500,
      "y": 400,
      "moveX": 500,
      "moveY": 400,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 500,
      "ogY": 400
    },
    {
      "x": 500,
      "y": 350,
      "moveX": 500,
      "moveY": 350,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 500,
      "ogY": 350
    },
    {
      "x": 500,
      "y": 300,
      "moveX": 500,
      "moveY": 300,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 500,
      "ogY": 300
    },
    {
      "x": 500,
      "y": 250,
      "moveX": 500,
      "moveY": 250,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 500,
      "ogY": 250
    },
    {
      "x": 500,
      "y": 450,
      "moveX": 500,
      "moveY": 450,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 500,
      "ogY": 450
    },
    {
      "x": 500,
      "y": 500,
      "moveX": 500,
      "moveY": 500,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 500,
      "ogY": 500
    },
    {
      "x": 500,
      "y": 550,
      "moveX": 500,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 500,
      "ogY": 550
    },
    {
      "x": 500,
      "y": 600,
      "moveX": 500,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 500,
      "ogY": 600
    },
    {
      "x": 500,
      "y": 650,
      "moveX": 500,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 500,
      "ogY": 650
    },
    {
      "x": 350,
      "y": 550,
      "moveX": 350,
      "moveY": 550,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 350,
      "ogY": 550
    },
    {
      "x": 350,
      "y": 600,
      "moveX": 350,
      "moveY": 600,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 350,
      "ogY": 600
    },
    {
      "x": 350,
      "y": 650,
      "moveX": 350,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 350,
      "ogY": 650
    },
    {
      "x": 250,
      "y": 650,
      "moveX": 250,
      "moveY": 650,
      "moveSpeed": 5,
      "trollMomentX": null,
      "trollMomentY": null,
      "trolledYet": false,
      "trollRadius": 10,
      "moveBack": false,
      "doneMoving": false,
      "ogX": 250,
      "ogY": 650
    }
  ],
  "spikes": [],
  "ziplines": [
    {
      "pt1X": 400,
      "pt1Y": 450,
      "pt2X": 650,
      "pt2Y": 450,
      "justJumpedOff": false,
      "jumpOffTimer": 0
    }
  ]
};